- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
      - openstackclient-plugin-jobs
    name: openstack/python-ironic-inspector-client
    check:
      jobs:
        - openstack-tox-functional
        - python-ironic-inspector-client-tempest-dsvm
    gate:
      jobs:
        - openstack-tox-functional
        - python-ironic-inspector-client-tempest-dsvm
