- project:
    templates:
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-functional-py36
        - python-ironic-inspector-client-tempest-python3
    gate:
      jobs:
        - openstack-tox-functional-py36
        - python-ironic-inspector-client-tempest-python3
